apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: micropowermanager-cloud

resources:
  - namespace.yaml
  - ../../base/gcp_gke/

components:
  - ../../components/internal_ingress

images:
  - name: enaccess/micropowermanager-backend:latest
    newTag: 0.0.47
  - name: enaccess/micropowermanager-frontend:latest
    newTag: 0.0.47
  - name: enaccess/micropowermanager-scheduler:latest
    newTag: 0.0.47

patches:
  - path: configmap-cloud-backend.yaml
    target:
      kind: ConfigMap
      name: mpm-configmap-backend
  - path: configmap-cloud-frontend.yaml
    target:
      kind: ConfigMap
      name: mpm-configmap-frontend
  # Setting a static IP external address for our external loadbalancer, see
  # https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#use_an_ingress
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: mpm-ingress
        annotations:
          kubernetes.io/ingress.global-static-ip-name: loadbalancer-global-address-cloud
  # Setting a static internal IP address and TLS for our internal loadbalancer, see
  # https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress#static_ip_addressing
  # https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balance-ingress#https_between_client_and_load_balancer
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: mpm-ingress-internal
        annotations:
          ingress.gcp.kubernetes.io/pre-shared-cert: internal-loadbalancer-cert-cloud
          kubernetes.io/ingress.regional-static-ip-name: internal-loadbalancer-address-cloud
  - patch: |-
      apiVersion: networking.gke.io/v1
      kind: ManagedCertificate
      metadata:
        name: mpm-managed-cert
      spec:
        domains:
          - api.cloud.micropowermanager.io
          - cloud.micropowermanager.io

replacements:
  - source:
      kind: ManagedCertificate
      name: mpm-managed-cert
      fieldPath: spec.domains.0
    targets:
      - select:
          kind: Ingress
          name: mpm-ingress
        fieldPaths:
          - spec.rules.0.host
  - source:
      kind: ManagedCertificate
      name: mpm-managed-cert
      fieldPath: spec.domains.1
    targets:
      - select:
          kind: Ingress
          name: mpm-ingress
        fieldPaths:
          - spec.rules.1.host
