apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpm-frontend
  template:
    metadata:
      labels:
        app: mpm-frontend
    spec:
      containers:
        - name: mpm-frontend
          image: enaccess/micropowermanager-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: MPM_ENV
              value: demo
            - name: MPM_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: mpm-secrets
                  key: MPM_BACKEND_URL
