<?php

namespace App\Console\Commands;

use App\Models\DatabaseProxy;
use Illuminate\Console\Command;
use Illuminate\Database\Eloquent\Collection;
use MPM\DatabaseProxy\DatabaseProxyManagerService;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

abstract class AbstractSharedCommand extends Command
{

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        /** @var DatabaseProxyManagerService $databaseProxyManagerService */
        $databaseProxyManagerService = app()->make(DatabaseProxyManagerService::class);

        return (int)$databaseProxyManagerService->queryAllConnections()->chunkById(50, function (Collection $modelCollection) use ($databaseProxyManagerService, $input, $output) {
            return $modelCollection->map(function (DatabaseProxy $databaseProxy) use ($databaseProxyManagerService, $input, $output) {
                $this->info("Running " . $this->name . " for company ID : " . $databaseProxy->getCompanyId());
                return $databaseProxyManagerService->runForCompany($databaseProxy->getCompanyId(), function () use ($input, $output) {
                    return parent::execute($input, $output); // TODO: Change the autogenerated stub
                });
            })->sum();
        });


    }
}
