apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps.yaml
  - redis.yaml
  - deployments.yaml
  - storage-pvc.yaml
  - services.yaml
  - ingress.yaml
  - egress-nat-policy.yaml
