apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpm-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo  # GCP standard storage class
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpm-logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo  # GCP standard storage class
