<?php

namespace App\Models;

use App\Models\Base\BaseModelCentral;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * API Keys can be generated by users to link third-party services allowing them to access certain MPM features.
 *
 * Example: A plugin can use generated API key to fetch payment data from MPM for exporting purposes.
 *
 * This model is used to store the API keys and their associated companies.
 *
 * These keys are secure and used by the API key guard to authenticate external requests to MPM.
 *
 * @property int     $id
 * @property int     $company_id
 * @property string  $token_hash
 * @property bool    $active
 * @property string  $name
 * @property string  $last_used_at
 * @property Company $company
 */
class ApiKey extends BaseModelCentral {
    protected $table = 'api_keys';

    protected $fillable = [
        'name',
        'token_hash',
        'active',
        'last_used_at',
    ];

    /**
     * @return BelongsTo<Company, $this>
     */
    public function company(): BelongsTo {
        return $this->belongsTo(Company::class);
    }

    /**
     * Scope query to only include active API keys.
     *
     * @param Builder<ApiKey> $query
     *
     * @return Builder<ApiKey>
     */
    #[Scope]
    protected function active(Builder $query): Builder {
        return $query->where('active', true);
    }
}
