apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-db
spec:
  selector:
    matchLabels:
      app: maria-db
  template:
    metadata:
      labels:
        app: maria-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.3
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mpm-secrets
                  key: DB_PASSWORD
            - name: MYSQL_DATABASE
              value: micro_power_manager
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: mpm-secrets
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              value: "3306"
          ports:
            - name: mariadb
              containerPort: 3306
