apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpm-frontend
  template:
    metadata:
      labels:
        app: mpm-frontend
    spec:
      containers:
      - name: mpm-frontend
        image: 905418087090.dkr.ecr.eu-central-1.amazonaws.com/mpm-ui
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: VUE_APP_MPM_BACKEND_URL
            value: http://a1c6c34afc2de48b3a3383b66e4206c0-1766560540.eu-central-1.elb.amazonaws.com

