apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mpm-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mpm-backend
    spec:
      containers:
      - env:
        - name: APP_NAME
          value: MicroPowerManager
        - name: APP_ENV
          value: demo
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              key: APP_KEY
              name: mpm-secrets
        - name: APP_DEBUG
          value: "false"
        - name: MPM_LOAD_DEMO_DATA
          value: "true"
        - name: DB_CONNECTION
          value: micro_power_manager
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: mpm-secrets
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          value: micro_power_manager
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: mpm-secrets
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: mpm-secrets
        - name: REDIS_HOST
          value: redis-db-service
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: JWT_SECRET
              name: mpm-secrets
        - name: CACHE_DRIVER
          value: redis
        - name: QUEUE_DRIVER
          value: database
        image: enaccess/micropowermanager-backend:latest
        imagePullPolicy: Always
        name: mpm-backend
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-12-13T05:47:18Z"
    lastUpdateTime: "2024-12-13T05:47:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-12-13T05:46:55Z"
    lastUpdateTime: "2024-12-13T05:47:18Z"
    message: ReplicaSet "mpm-backend-7b59564f89" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
