apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpm-frontend
  template:
    metadata:
      labels:
        app: mpm-frontend
    spec:
      containers:
      - name: mpm-frontend
        image: 905418087090.dkr.ecr.eu-central-1.amazonaws.com/mpm-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: VUE_APP_MPM_BACKEND_URL
            value: https://backend-demo.micropowermanager.io
        
