apiVersion: v1
kind: Service
metadata:
  name: mpm-backend-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: mpm-backend
