name: Check Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-terraform-fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        id: fmt
        run: terraform fmt -recursive -diff -check
        working-directory: terraform
