name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./Website/ui

      - name: Run ESLint
        run: npm run lint
        working-directory: ./Website/ui

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./Website/ui

      - name: Run Prettier
        run: npm run prettier
        working-directory: ./Website/ui

  build-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.10.0

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./Website/ui

      - name: Build npm on production mode
        run: npm run build
        working-directory: ./Website/ui
