name: ERD Generate Check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ["8.2"]

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_DATABASE: micro_power_manager
          MYSQL_ROOT_PASSWORD: wF9zLp2qRxaS2e
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ERD database
        run: docker exec $(docker ps -q -f ancestor=mysql:8.4) mysql -u root -pwF9zLp2qRxaS2e -e "CREATE DATABASE IF NOT EXISTS erd;"

      - name: Generate ERD for micro_power_manager
        run: php artisan erd:generate micro_power_manager --excludes=plugins --file=central_database.sql

      - name: Generate ERD for tenant
        run: php artisan erd:generate tenant --path=/database/migrations/tenant --excludes=companies,company_databases,company_jobs,database_proxies --file=tenant_database.sql

      - name: Upload ERD files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: erd-files
          path: |
            central_database.sql
            tenant_database.sql
