name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip
          tools: composer:2.6

      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction --prefer-dist
        working-directory: ./Website/htdocs/mpmanager

      - name: Run PHP-CS-Fixer
        run: composer run php-cs-fixer-check
        working-directory: ./Website/htdocs/mpmanager

      - name: Run PHPStan
        run: composer run phpstan-analyze
        working-directory: ./Website/htdocs/mpmanager
        continue-on-error: true

      - name: Run Psalm
        run: composer run psalm-check
        working-directory: ./Website/htdocs/mpmanager
        continue-on-error: true
