name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip

      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction --prefer-dist
        working-directory: ./src/backend

      - name: Run PHP-CS-Fixer
        run: composer php-cs-fixer-check
        working-directory: ./src/backend

      - name: Run PHPStan
        run: composer phpstan-analyse
        working-directory: ./src/backend

        # Temporarily disabled, until we can run it with php-parser version 5
        # https://github.com/vimeo/psalm/issues/11112
        # - name: Run Psalm
        #   run: composer psalm-check
        #   working-directory: ./src/backend
        #   continue-on-error: true
