name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, zip

      - name: Install Composer Dependencies
        run: |
          composer install --no-interaction --prefer-dist
        working-directory: ./src/backend

      - name: Run PHP-CS-Fixer
        run: composer php-cs-fixer-check
        working-directory: ./src/backend

      - name: Run PHPStan/Larastan
        run: composer larastan
        working-directory: ./src/backend

      - name: Run PHPStan/Larastan (Packages)
        run: composer larastan-packages
        working-directory: ./src/backend

      - name: Run PHPStan/Larastan (next level)
        run: composer larastan-next
        working-directory: ./src/backend
        continue-on-error: true

      - name: Run Rector
        run: composer rector-check-github
        working-directory: ./src/backend
        continue-on-error: true
