name: Deploy to EKS

on:
  release:
    types:
      - published
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Authenticate kubectl with EKS
        run: |
          aws eks update-kubeconfig --region eu-central-1 --name mpm

      - name: Deploy to EKS
        run: |
          if kubectl get deployment mpm-backend; then
            kubectl rollout restart deployment/mpm-backend
          else
            echo "mpm-backend deployment does not exist, applying initial deployment..."
            kubectl apply -f k8s/deployments/mpm-backend.yaml
          fi

          if kubectl get deployment mpm-frontend; then
            kubectl rollout restart deployment/mpm-frontend
          else
            echo "mpm-frontend deployment does not exist, applying initial deployment..."
            kubectl apply -f k8s/deployments/mpm-frontend.yaml
          fi


