name: Update DockerHub description

on:
  # release:
  #   types:
  #     - published
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - repo: enaccess/micropowermanager-frontend
            dockerfile: ./docker/DockerfileFrontendProd
          - repo: enaccess/micropowermanager-backend
            dockerfile: ./docker/DockerfileBackendProd

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME_LEGACY }}
          password: ${{ secrets.DOCKERHUB_TOKEN_LEGACY }}
          repository: ${{ matrix.image.repo }}
          short-description: Open Source Management Tool for Decentralized Utilities
